### ISSUE TITLE
Display: flex causes overflow

### ISSUE THREAD

**Issue by Jaskerv** [niuware/mui-rte#1]
I want to inline the label and the rte. So I tried using a flexbox however that causes the rte to overflow rather than new line. 

![image](https://user-images.githubusercontent.com/26532014/60930073-104c1c00-a308-11e9-9a33-e478d4bdfe74.png)

**Comment by niuware** [comment]
I used your sample code but both the editor and the `h1` tag are displayed inline as expected. Could you try installing the latest version and override the `root` class of the editor? Check out the `theme` example for more details on how to override the style. If you still have a rendering problem please feel free to reopen the issue.

**Comment by Jaskerv** [comment]
Sorry, I gave a bad example. 

The issue occurs when the parent div is this:
`<div style={{ display: "flex", flexDirection: "row" }}>`
and the text being typed has no spaces.
Example: `SomeGiantText` pasted 20 with no spaces.

**Expected Behaviour** 
When typing the above text to new-line when the text reaches near the edge of the container.
![image](https://user-images.githubusercontent.com/26532014/61335285-0d5da800-a881-11e9-82dd-3833a8ec6575.png)

**Actual Behaviour**
![image](https://user-images.githubusercontent.com/26532014/61335530-e9e72d00-a881-11e9-9ddb-ec498c13dd65.png)
You can see it overflows with the horizontal scrollbar.

[Codesandbox](https://codesandbox.io/s/mui-rte-basic-5zhwv?fontsize=14)

**Comment by niuware** [comment]
I've just opened your CodeSandbox sample, pasted the text more than 20 times as well as input a random long string without spaces and in both cases the result behaviour is as expected. By default the width of the editor is same as its parent and the content is wrapped correctly.
