### ISSUE TITLE
feature request: support draft decorators

### ISSUE THREAD

**Issue by TrejGun** [niuware/mui-rte#105]
Hi guys
you have support for decorators already but it does not work with draft decorators liek this one
https://github.com/SamyPesse/draft-js-prism
may be you can remove 
```
        props.decorators.forEach(deco => decorators.push({
            strategy: (contentBlock: any, callback: any) => {
                findDecoWithRegex(deco.regex, contentBlock, callback)
            },
            component: deco.component
        }))
```
wrap current decorators in example folder in [simpledecorator](https://github.com/Soreine/draft-js-simpledecorator) 
and allow to use draft decorators directly?

**Comment by niuware** [comment]
I believe the library you provide does not conform to a `DraftDecorator` instance so cannot be used with the current `draft-js` version.

You still can create decorators just as `draft-js-simpledecorator` works and do further customization in a provided custom component. If a [custom decorator](https://github.com/niuware/mui-rte/blob/master/examples/decorator/index.tsx) is not enough, you can consider using [custom atomic blocks](https://github.com/niuware/mui-rte/blob/master/examples/atomic-custom-block/index.tsx) to enable further customization.
