### ISSUE TITLE
Content is removed when creating URL in chrome.

### ISSUE THREAD

**Issue by Destidom** [niuware/mui-rte#11]
When aliasing an URL in chrome the alias is removed when you press space or enter. When starting to type again the first character of the word will have the href tag on it, but not the whole word.
It looks like this
![image](https://user-images.githubusercontent.com/1110208/62927315-96033180-bdb6-11e9-955a-e47347b4d09a.png)
Only the Y becomes clickable after we try to write the name again after it has been removed.

This behavior does not exists in Firefox, edge dev or edge. 
I'm not sure if this is a mui-rte issue or a draftjs issue though.

**Comment by niuware** [comment]
@Destidom This issue was addressed in version 1.1.1. Can you confirm this is happening in the latest version (>= 1.1.1)?

**Comment by Destidom** [comment]
Ah, yeah it is working in version 1.1.1. Sorry for the inconvenience and thanks for a swift reply.
