### ISSUE TITLE
onChange not working 

### ISSUE THREAD

**Issue by Abinaskarki** [niuware/mui-rte#12]
i am trying to pass the text inside mui-rte to the state using onChange where I have passed handleChange function which takes a prop and changes that value to the state. However, it is giving this error `
TypeError: Cannot read property 'value' of `undefined``

Here is my code: 
```
 const [Ques, setQues] = useState({
    answer: '',
    question: ''
  });

  const handleChange = prop => event => {
    setQues({ ...Ques, [prop]: event.target.value });
    console.log(event.target.value);
  };
<MUIRichTextEditor
            label="Start Typing ..."
            controls={[
              'title',
              'bold',
              'italic',
              'underline',
              'strikethrough',
              'highlight',
              'undo',
              'redo',
              'save'
            ]}
            value={Ques.answer}
            onChange={handleChange('answer')}
            className="p-1"
          />

```Any suggestion would be highly appreciated.

**Comment by niuware** [comment]
The `onChange` property expects a callback of type `(state: Draft.Model.ImmutableData.EditorState) => void`. You are currently expecting `event` to be the incorrect type. To access the typed text you have to do as follows:

```js

const handleChange = prop => event => {
    // `event` is of type Draft.Model.ImmutableData.EditorState
    //
    // Use `getPlainText` method to get the text
    // https://draftjs.org/docs/api-reference-content-state#getplaintext
    const text = event.getCurrentContent().getPlainText()
    setQues({ ...Ques, [prop]: text });
    console.log(text);
};
```

Hope it helps! Thanks for using this component :)

**Comment by Abinaskarki** [comment]
**Thank you for your suggestion. It still does not work for me. I get "block is not a BlockNode" error**
`
import { convertToRaw } from 'draft-js';
const Editor = () => {
  const [Ques, setQues] = useState({
    answer: '',
    question: ''
  });

  const handleChange = prop => event => {
    const content = JSON.stringify(convertToRaw(event.getCurrentContent()));
    setQues({ ...Ques, [prop]: content });
    console.log(content);
  };
const handleSubmit = () => {};
<form onSubmit={handleSubmit} className="p-2">
        <div className="p-2">
          <MUIRichTextEditor
            label="Start Typing ..."
            controls={[
              'title',
              'bold',
              'italic',
              'underline',
              'strikethrough',
              'highlight',
              'undo',
              'redo',
              'save'
            ]}
            value={Ques.answer}
            onChange={handleChange('answer')}
            className="p-1"
          />
        </div>
        <div className="my-8">
          <button className="bg-green-500 p-1 text-white font-bold">
            {' '}
            Answer{' '}
          </button>
        </div>
      </form>
`

![error](https://user-images.githubusercontent.com/24517247/63509943-62f22980-c4ab-11e9-8d19-b52ce5d06bf7.PNG)

Any comments would be highly appreciated.

**Comment by niuware** [comment]
@Abinaskarki In your code setting the `value` property has no effect after the component has already loaded as this property is only used to set a default value at load time. The minimum version of `draft-js` for this component is `0.10.5` so using a previous version may have unexpected behaviour.

**Comment by Abinaskarki** [comment]
Hi @niuware , when I use draft-js 0.10.5, I get this error.
`block is not a BlockNode
▶ 9 stack frames were collapsed.
onChange
D:/visa_platform-client_app/src/components/Editor.js:13
  10 |  });
  11 | 
  12 |  const handleChange = prop => event => {
> 13 |    const content = JSON.stringify(convertToRaw(event.getCurrentContent()));
     | ^  14 |    // const content = event.getCurrentContent().getPlainText();
  15 |    setQues({ ...Ques, [prop]: content });
  16 |  };
View compiled
▶ 24 stack frames were collapsed.`

I tried removing value property from mui-rte component. But, it does no t work. how, would I tackle this error on draft-js 0.10.5
