### ISSUE TITLE
How can I override the normal controls?

### ISSUE THREAD

**Issue by Kauyumari** [niuware/mui-rte#121]
I'm trying to change how the save button looks in the editor but I simply can't find a way where I could just override the Save icon.

I'm trying to build a customControl but the props returned don't suit what I need to do. All I need is to have the same behavior as the Save button. 

I can't use the editor ref and can't save the state returned in the callback. I have a lot of editors across my app and I need a one-for-all configuration.

**Comment by niuware** [comment]
Hi @Kauyumari 
You cannot "override" the default controls but you can replicate all default controls functionalities with the provided API. Also you can add set the `id` property if you have multiple editors.

If you want to create your own `Save` button, you can use a `callback` custom control and when you click it you will get all necessary parameters to replicate the functionality. 

This is the `onClick` event API: 

`(editorState: EditorState, name: string, anchor: HTMLElement | null) => EditorState | void`

Just use the `editorState` instance to replicate the internal [save](https://github.com/niuware/mui-rte/blob/master/src/MUIRichTextEditor.tsx#L523) feature.

Find a full example of callback custom controls [here](https://github.com/niuware/mui-rte/blob/master/examples/custom-controls/index.tsx#L84). 

Hope this helps you out!
