### ISSUE TITLE
Decorators reset the cursor to beginning of the text

### ISSUE THREAD

**Issue by narghev** [niuware/mui-rte#127]
There seems to be an issue with custom decorators. Whenever I get a match, the decorator works correctly (_renders my custom decorator_) but resets the cursor. I verified the issue on `codesandbox` to make sure that the issue is not related to my codebase.

```js
import React from "react";
import ReactDOM from "react-dom";
import MUIRichTextEditor from "mui-rte";

ReactDOM.render(
  <MUIRichTextEditor
    label="Type something here..."
    decorators={[
      {
        component: ({ decoratedText }) => (
          <span style={{color: 'red'}}>{decoratedText}</span>
        ),
        regex: /hello/g,
      }
    ]}
  />,
  document.getElementById("root")
);
```

Additionally, if the `regex` is __NOT__ global it crashes the website. Again, verified on `codesandbox`.

```js
import React from "react";
import ReactDOM from "react-dom";
import MUIRichTextEditor from "mui-rte";

ReactDOM.render(
  <MUIRichTextEditor
    label="Type something here..."
    decorators={[
      {
        component: ({ decoratedText }) => (
          <span style={{color: 'red'}}>{decoratedText}</span>
        ),
        regex: /hello/,
      }
    ]}
  />,
  document.getElementById("root")
);
```

**Comment by narghev** [comment]
Hi @niuware, do you know how I can solve this problem? Thanks

**Comment by niuware** [comment]
Hi @narghev you should not use `decoratedText` as the output to render, use `children` instead:
```
{
    component: ({ children }) => (
        <span style={{color: 'red'}}>{children}</span>
    ),
    regex: /hello/g,
}
```

> Additionally, if the regex is NOT global it crashes the website.

What is the problem with this?

Hope this helps you out.
