### ISSUE TITLE
Type 'EditorState' is not assignable to type 'null'

### ISSUE THREAD

**Issue by claitonnazaret** [niuware/mui-rte#133]
TypeScript error in G:/sgp/web-app/node_modules/mui-rte/src/MUIRichTextEditor.tsx(754,13):
Type 'EditorState' is not assignable to type 'null'.  TS2322

in MUIRichTextEditor.tsx:747 change line let replaceEditorState = null; to let replaceEditorState;

in utils.ts:24 change line let entityType = null; to let entityType = '';

**Comment by niuware** [comment]
Hi @claitonnazaret, I need more context for this but I am guessing this is related with your typescript configuration, although even with `strictNullChecks` enabled, the compilation does not have any problems.

**Comment by claitonnazaret** [comment]
My compilation presents this error message
![image](https://user-images.githubusercontent.com/3700216/84023657-df80c680-a95e-11ea-9bf9-5a5aaf129747.png)

My tsconfig:

![image](https://user-images.githubusercontent.com/3700216/84023795-1eaf1780-a95f-11ea-87a8-a224e4fb2958.png)

**Comment by niuware** [comment]
I pushed an update and this should be fixed on version `1.19.2`. Please check it out.

**Comment by claitonnazaret** [comment]
Version 1.19.2 corrected the error Type 'EditorState' is not assignable to type 'null', but a new error appeared in the utils.ts file on line 24 that starts the entityType variable with null. When changing to '' the error is corrected according to the prints below:

![image](https://user-images.githubusercontent.com/3700216/84101425-501df680-a9e4-11ea-897c-d6dc200cd106.png)

The line: 

![image](https://user-images.githubusercontent.com/3700216/84101467-662bb700-a9e4-11ea-807b-47ae20391001.png)

Correction: 

![image](https://user-images.githubusercontent.com/3700216/84101533-89566680-a9e4-11ea-990c-05710897bc4d.png)

Appreciate...

**Comment by niuware** [comment]
Missed the second one you wrote on your comment. 

Should be fixed on version `1.19.3`. Please check it out.
