### ISSUE TITLE
How to add alignment control to a title without losing style?

### ISSUE THREAD

**Issue by SEVGAR** [niuware/mui-rte#135]
I discovered mui-rte which perfectly links DraftJS and Material-UI, but I can't choose the alignment of the title block: the style is lost when the block is aligned.

Here my title : 
`{
            name: "Title1",
            icon:  <TitleIcon number="1" />,
            type: "block",
            blockWrapper: <MonT1 />
        },`
and the blockWrapper : 
`const MonT1 = (props)=> {return (<h4 className='MuiTypography-h4' style={{margin: '10px 0'}}>{props.children}</h4>);};`
 If I create another "center" block, the "Title1" block is replaced, and if I create an "Center" inline style, the "Title1" block is not aligned correctly.
How should I do it?

**Comment by niuware** [comment]
Hi @SEVGAR , sorry I can't understand what is your problem. You wan't a centered title block? Just use the correct style for your block:
```
<h4 className='MuiTypography-h4' style={{margin: '10px 0', textAlign: "center"}}>. 
    {props.children}
</h4>
```

Hope this helps.

**Comment by SEVGAR** [comment]
140/5000
In fact, I want to add an alignment control "center", "left", "right" which adds the style = {{textAlign: my choice}} in my title : is it possible?

**Comment by niuware** [comment]
Now I understand. Yes it is possible but you are trying to apply 2 different block styles to the same content, so that is not possible. What you can do is create custom blocks for each alignment you need and then use custom inline styles for the _Title_ style (a block can have different inline styles).

**Comment by SEVGAR** [comment]
Thanks ! I understand now, it work!
Another thing : is it possible to overwrite the style of link? 
Default : `style="text-decoration: underline;color: inherit;"`

**Comment by niuware** [comment]
>is it possible to overwrite the style of link?

Yes, you can either create your own [custom control](https://github.com/niuware/mui-rte/blob/master/examples/custom-controls/index.tsx) with a link functionality or add an `a` tag CSS style to your page.

**Comment by SEVGAR** [comment]
I'd like to overwrite your example : 
`{
            label: 'Link',
            name: "link",
            style: 'LINK',
            inlineStyle: {color: "red"},
            icon: <InsertLinkIcon />,
            type: "callback",
            id: "link-control"
        },`
the inlineStyle doesn't work ... and the tag CSS doesn't work because the default style overwrite this tag.
Default style : 
`const Link: FunctionComponent<TLinkProps> = (props) => {
    const { url } = props.contentState.getEntity(props.entityKey).getData()
    return (
        <a 
            href={url} 
            style={{
                textDecoration: "underline",
                color: "inherit"
            }} 
            className="editor-anchor"
            target="_blank"
        >
            {props.children}
        </a>
    )
}`
Thank for your help

**Comment by niuware** [comment]
> I'd like to overwrite your example :

You cannot do that, as the _LINK_ is a decorator not a custom control. The links have a `editor-anchor` classname by default, have you tried applying your style to this CSS class?

**Comment by SEVGAR** [comment]
With the CSS class `editor-anchor`, I can add properties but not change `textDecoration: "underline", color: "inherit"`, style comes first : 
![image](https://user-images.githubusercontent.com/53193592/84806976-d222a680-b006-11ea-8de3-11d04cfc56e5.png)
and it's a shame not to use Material-UI

**Comment by niuware** [comment]
There was an `anchorLink` class but it was not properly set up with the `Link` component. Now you can override the `anchorLink` class with your custom style from version `1.21.0`. Check out the [updated example](https://github.com/niuware/mui-rte/blob/master/examples/theme/index.tsx) for more details.

**Comment by corneliugaina** [comment]
I'm trying to create a custom control that will center the line (or selected line), like text-align: "center". Pretty simple, the editor proceed to center my block, but when I log the value, it's still a simple < p >content</ p >. 

So the next time it renders (after saving and storing the EditorState, that is manipulated further), it loose the "centered style".

I tried several customControls, like "block" with a simple blockWrapper (works on editor but logged block is stil wrapperd in <p> whitout style);  or "inline" (this doesn't work at all).

I would like to hard-code the centering style in styleRenderMap along HIGHLIGHT and STRIKETROUGH, but cannot find how.

**Comment by MrRainesE** [comment]
> 140/5000 In fact, I want to add an alignment control "center", "left", "right" which adds the style = {{textAlign: my choice}} in my title : is it possible?

do you have a working example of this? i try this but its not working
```
customControls={[
                {
                    name: "align-center",
                    icon: <AlignCenter />,
                    type: "inline",
                    inlineStyle: {
                       text-align:'center'
                    }
                }
            ]}
```
