### ISSUE TITLE
How to get html value from editor?

### ISSUE THREAD

**Issue by pavittar95** [niuware/mui-rte#138]
Hi, I'm trying to get HTML content from the editor but I cannot find any example or anything. Please help.

**Comment by niuware** [comment]
@pavittar95 This feature is not provided by `draft-js` nor this package.

**Comment by dohomi** [comment]
Just in case someone finds this issue and would like to receive HTML, make use of `draft-js-export-html` with following minimal example:
```js
import MUIRichTextEditor from 'mui-rte'
import { stateToHTML } from 'draft-js-export-html'

function MyRte(){
  let _editorState: any = null
  return(
    <MUIRichTextEditor
        label={'Type your message here...'}
        onChange={(state) => {
          _editorState = state
        }}
        onSave={()=>{
          const html = stateToHTML(_editorState.getCurrentContent()) // => here you gonna have HTML    
        }}
      />
  }
}
```
@niuware would it be possible to pass the `EditorState` beside the data string at the `onSave` function? That would make the use easier of getting the current state content.

**Comment by pavittar95** [comment]
@dohomi Yes, I have used `stateToHTML` for getting the HTML from the editor. Using ref to call the save method of the editor on button click will do the trick.

**Comment by dohomi** [comment]
I draft a small gist for a rte to receive HTML and TEXT:
https://gist.github.com/dohomi/a25f0c146537035dd0dca741403f6253

**Comment by albertolotz** [comment]
Hello all.
A would like a simple convert to HTML in save... but I dont know how convert data to ContentState.
Tks for help.

const save = (data: string) => {
    console.log(stateToHTML(data));
  };
