### ISSUE TITLE
List mismatch in controls

### ISSUE THREAD

**Issue by lancemccluskey** [niuware/mui-rte#139]
## Checklist

- [x] This is not covered in the [repository examples](https://github.com/niuware/mui-rte/tree/master/examples).
- [x] I am using the package [latest version](https://github.com/niuware/mui-rte/releases/latest).
- [x] This is a bug report or an enhancement proposal.

## Description

When setting the `controls` attribute the `bulletList` and `numberList` are flipped as shown in the screenshots below. 

<img width="780" alt="Screen Shot 2020-06-11 at 6 46 21 AM" src="https://user-images.githubusercontent.com/40124399/84381871-4694ba00-abaf-11ea-8e34-43a1a4d63cde.png">
<img width="791" alt="Screen Shot 2020-06-11 at 6 46 46 AM" src="https://user-images.githubusercontent.com/40124399/84381900-53b1a900-abaf-11ea-9a2c-1c0be1509d3d.png">

**Comment by niuware** [comment]
@lancemccluskey Thanks for reporting the issue. This was fixed on version `1.20.0`.
