### ISSUE TITLE
Read-only is moving focus to the end of the page 

### ISSUE THREAD

**Issue by joaoaguiam** [niuware/mui-rte#142]
## Checklist

- [x] This is not covered in the [repository examples](https://github.com/niuware/mui-rte/tree/master/examples).
- [x] I am using the package [latest version](https://github.com/niuware/mui-rte/releases/latest).
- [x] This is a bug report or an enhancement proposal.

## Description

Since version 1.20, my read-only page is no longer being shown with the scroll at the top of the page as it was before. Looking to the latest commit it seems that you are forcing the focus of the editor to the end which may be causing this issue. 

If you need more details just let me know.

**Comment by niuware** [comment]
@joaoaguiam Thanks for the issue comment. It should be fixed on version `1.21.0`.
