### ISSUE TITLE
Typescript error (TS4023) when compiling with Rollup

### ISSUE THREAD

**Issue by andy-mcdonald** [niuware/mui-rte#144]
## Description

I'm trying to use the editor in a component library bundled with Rollup (using @rollup/plugin-typescript) but the build fails with the following error:

```[!] (plugin typescript) Error: @rollup/plugin-typescript TS4023: Exported variable 'getEditorBounds' has or is using name 'Draft.Component.Selection.FakeClientRect' from external module "/Users/andy/Code/scrap/monorepo/node_modules/@types/draft-js/index" but cannot be named.```
```
../../node_modules/mui-rte/src/utils.ts (87:7)

const getEditorBounds = (editor: HTMLElement) => {
```

My component is basically just the simplest 'Hello World' implementation:

```
import React from 'react'
import MUIRichTextEditor from 'mui-rte'

const RichTextEditor = () => {
  const onSave = (data) => {
    console.log(data)
  }

  return (
    <MUIRichTextEditor
      label='Type something here...'
      onSave={onSave}
      inlineToolbar={true}
    />
  )
}

export default RichTextEditor
```

**Comment by niuware** [comment]
Hi @andy-mcdonald I think this is more related to your rollup configuration. Probably the problem is the `Draft.Component.Selection.FakeClientRect` is not explicitly imported into the `utils.ts` file. Currently this type is not exported from the _@types_ definitions of `draft-js`.

**Comment by andy-mcdonald** [comment]
Thanks for looking into this Erik. I think you are right so I'll keep digging into it. Very well constructed library by the way!

**Comment by sajadghawami** [comment]
Hey,

**Comment by arvinsim** [comment]
Having the same problem here too.
