### ISSUE TITLE
Material-UI Link styles

### ISSUE THREAD

**Issue by mmaass** [niuware/mui-rte#147]
## Checklist

- [x] This is not covered in the [repository examples](https://github.com/niuware/mui-rte/tree/master/examples).
- [x] I am using the package [latest version](https://github.com/niuware/mui-rte/releases/latest).
- [x] This is a bug report or an enhancement proposal.

## Description
Good job with the editor, we are very fond of it ❤️

I am aware of the fact that you can customise the RTE via a theme as done here (https://github.com/niuware/mui-rte/blob/master/examples/theme/index.tsx)

<img width="558" alt="link-styling" src="https://user-images.githubusercontent.com/576477/85037727-096b9180-b186-11ea-8ffb-6d0909a1725c.png">

As you can see in the screenshot I've attached, the styling of an actual Link (materialUI component) and a link in the MUIRichTextEditor isn't equal. Given the name of the this project I was under the assumption, that the content of the RTE would be rendered with MaterialUI styling. Instead the MaterialUI styling seems to be restricted to the Toolbar and the Popups.

**Question:**
Do I have to mimic MaterialUI's Link styles in a custom theme for the MUIRichTextEditor or can I override the DOM created if a Link gets inserted in the RTE. - or is there even another way I've missed so far?

**Enhancement**
The RTE content not being rendered with MaterialUI styles could be better communicated in the project's readme file.

**Comment by niuware** [comment]
Hi @mmaass 
Thanks for using the package. Indeed the `Link` component of the `MUIRichTextEditor` should be using the `Link`'s component from `material-ui`. I have updated this on version `1.23.0`, but as for now you won't be able to be set properties like `variant`, `color`, etc., but instead rely on a custom theme.

**Comment by mortoni** [comment]
Hi @niuware,

How can I change the link color when it is visited inside custom theme?

**Comment by niuware** [comment]
Hi @mortoni, you can use nested selectors:

```
anchorLink: {
    color: "#FF0000",
    "&:visited": {
        color: "#00FF00"
    }
}
```
