### ISSUE TITLE
Can I force the first line to be a different style?

### ISSUE THREAD

**Issue by shamoons** [niuware/mui-rte#155]
## Checklist

- [x] This is not covered in the [repository examples](https://github.com/niuware/mui-rte/tree/master/examples).
- [x] I am using the package [latest version](https://github.com/niuware/mui-rte/releases/latest).
- [x] This is a bug report or an enhancement proposal.

## Description

I want it to be like `medium`, where the first line is a title. Can this be forced somehow?

**Comment by niuware** [comment]
You can use the `defaultValue` property for this.

This is not a bug or enhancement.
