### ISSUE TITLE
How can I intercept a keystroke?

### ISSUE THREAD

**Issue by shamoons** [niuware/mui-rte#156]
## Checklist

- [x] This is not covered in the [repository examples](https://github.com/niuware/mui-rte/tree/master/examples).
- [x] I am using the package [latest version](https://github.com/niuware/mui-rte/releases/latest).
- [x] This is a bug report or an enhancement proposal.

## Description

Specifically, I want to catch when the `tab` key is pressed.

**Comment by niuware** [comment]
Please read the provided [example](https://github.com/niuware/mui-rte/blob/master/examples/key-bindings/index.tsx).

This is not a bug or enhancement.
