### ISSUE TITLE
When i convert the content to HTML format, highlight tags go missing.

### ISSUE THREAD

**Issue by Khushboo-Mishra** [niuware/mui-rte#159]
const contentHTML = convertFromHTML(editor_text);
            const state = ContentState.createFromBlockArray(contentHTML.contentBlocks, contentHTML.entityMap);
            const content = JSON.stringify(convertToRaw(state));

Here is the sample image 

![image](https://user-images.githubusercontent.com/20061077/86227487-b55fa480-bbaa-11ea-8e0d-4ffe8bdc9072.png)

When converted to HTML:

<p><del><strong>Hello </strong></del><del>[=PercentageDiscount] [=FixedAmountDiscount]&nbsp;</del></p>
<ul>
  <li>[=PercentageDiscount]</li>
</ul>
<p><em>[=FixedAmountDiscount]</em></p>
<p>[=PercentageDiscount]</p>
<p>[=FixedAmountDiscount]</p>

As clear, other styling is there except highlighting.

**Comment by niuware** [comment]
Seems this is a problem of your HTML converter.
