### ISSUE TITLE
Support for custom styles?

### ISSUE THREAD

**Issue by rasjonell** [niuware/mui-rte#16]
Hey there. First of all thanks for this package, it was really straightforward to integrate with our current MUI-based codebase.

I've been going through the source [code](https://github.com/niuware/mui-rte/blob/master/src/MUIRichTextEditor.tsx#L18) and noticed that the styles are hardcoded. I think it would be really handy if we could provide custom `classes` prop with the supported keys(i.e. container, editor, etc.).

Also it would be really helpful if the [EditorControls](https://github.com/niuware/mui-rte/blob/master/src/MUIRichTextEditor.tsx#L455) component had its own class.

**Comment by niuware** [comment]
Hi @rasjonell thanks for using this component. The styles are ready to be overridden using `Material-UI` theming feature. Have you take a look to the `theme` included [example](https://github.com/niuware/mui-rte/tree/master/examples/theme)? You just need to create your theme with `createMuiTheme` and override classes such as `root`, `container`, `editor`, and `editorContainer`. Does this help you out?

**Comment by rasjonell** [comment]
My bad didn't go over over the examples, this solves the problem. thanks a lot @niuware. Closing the issue.
