### ISSUE TITLE
Edit atomic-custom-block content after saved 

### ISSUE THREAD

**Issue by Igor2122** [niuware/mui-rte#160]
## Checklist

- [no] This is not covered in the [repository examples](https://github.com/niuware/mui-rte/tree/master/examples).
- [yes] I am using the package [latest version](https://github.com/niuware/mui-rte/releases/latest).
- [no] This is a bug report or an enhancement proposal.

## Description

What is the recommended way to edit values on the atomic-custom-block example after save?  Behaviour like on the async image upload, when clicked on card can edit the content with popOver?

**Comment by niuware** [comment]
Currently this is not yet supported. You would need to delete and create your block again.
