### ISSUE TITLE
Add https in url and caption on buttons

### ISSUE THREAD

**Issue by maanolfi** [niuware/mui-rte#161]
## Description

Hi,
We’re using the url popover component in order to add links to our textbox. The problem is that the link output is exactly what the user typed and, frequently, users type a link but without http:// or https:// which makes that as a relative link instead of an absolute one. I’d like of a parameter which would prepend the output link in order to deal or prevent such issue. The best probably would be to call a function before setting the link on draft state so that function could format the link as needed.

Thanks for the attention!

and

```
<Tooltip title={props.label} placement="top">
            <IconButton
                {...sharedProps}
                aria-label={props.label}
                color={props.active ? "primary" : "default"}
                size={size}
            >
                {props.icon}
                
            </IconButton>
            </Tooltip>
```

https://www.linkedin.com/in/maanolfi/

**Comment by niuware** [comment]
I understand, but seems this functionality is out of the scope of the text editor. Maybe is cleaner to create your own custom control with this functionality?
