### ISSUE TITLE
Blank is displayed when a JSX is specified as value in autocomplete strategies

### ISSUE THREAD

**Issue by poonamBattulwar** [niuware/mui-rte#168]
## Checklist

-  This is not covered in the [repository examples](https://github.com/niuware/mui-rte/tree/master/examples).
-  I am using the package [latest version](https://github.com/niuware/mui-rte/releases/latest).
- 

## Description
I am trying out the autocomplete strategy for mui-rte which is a great feature. As part of it I wanted to format the text and has given a jsx element as value , but when selected in editor, bank is displayed instead of element.

**Comment by niuware** [comment]
Can you add a snippet of your current implementation?

**Comment by poonamBattulwar** [comment]
Sure.. will share the code snippet

**Comment by poonamBattulwar** [comment]
Const testControl = <h1> Test </h1>
Const staff = [
{
 Key : [“foo”, “all”],
 Value : testControl,
 Content : “This is Test”
}
]

ReactDom.render(
<MUIRichTextEditor
  Label = “type here”
  autocomplete ={{
      strategies : [
             {
                 Items : staff,
                 triggerChar : “@“
               }
        ]
    }}
/>,
document.getElementById(“root”)
);

**Comment by niuware** [comment]
This snippet will never work as it is. Gonna close this issue for now.
