### ISSUE TITLE
Render atomic block inline

### ISSUE THREAD

**Issue by agavrilov** [niuware/mui-rte#173]
## Checklist

- [X] This is not covered in the [repository examples](https://github.com/niuware/mui-rte/tree/master/examples).
- [X] I am using the package [latest version](https://github.com/niuware/mui-rte/releases/latest).
- [ ] This is a bug report or an enhancement proposal.

## Description

I want to render an atomic block inline. How can I do it? In Draft.js, I could use custom block render map: https://draftjs.org/docs/advanced-topics-custom-block-render-map/. I don't see it exposed in mui-rte

**Comment by niuware** [comment]
Do you mean something like [this](https://github.com/niuware/mui-rte/blob/master/examples/atomic-custom-block/index.tsx)?
