### ISSUE TITLE
How to remove extra linebreak when adding an image

### ISSUE THREAD

**Issue by tinkermachine** [niuware/mui-rte#174]
## Checklist

- [ ] This is not covered in the [repository examples](https://github.com/niuware/mui-rte/tree/master/examples).
- [ ] I am using the package [latest version](https://github.com/niuware/mui-rte/releases/latest).
- [ ] This is a bug report or an enhancement proposal.

## Description

I am using the media control to upload an image into the editor, but the image seems to be preceded by a line break. I'd like to remove the linebreak, but when doing that the image also gets removed. How can I add an image without the mandatory preceding linebreak?

**Comment by niuware** [comment]
This is the expected behavior when adding a block, to enable the cursor after it is added.

**Comment by tactycadmin** [comment]
Second this suggestion. There are many instances where a text block starts with an image (a logo for e.g.) and it would be nice to have the option to remove the extra linebreak.
