### ISSUE TITLE
Is it possible to add a custom block to the content with its own editable fields?

### ISSUE THREAD

**Issue by remcohh** [niuware/mui-rte#177]
## Checklist

- [ ] This is not covered in the [repository examples](https://github.com/niuware/mui-rte/tree/master/examples).
- [ ] I am using the package [latest version](https://github.com/niuware/mui-rte/releases/latest).
- [ ] This is a bug report or an enhancement proposal.

## Description

I tried to add a simple block with an input in it but when I try to give it focus, that seems to be impossible
I am not sure if this is even possible? I can't find an example like that

**Comment by niuware** [comment]
Indeed, this is currently not possible.
