### ISSUE TITLE
Support for MUI v5 early versions

### ISSUE THREAD

**Issue by gurkerl83** [niuware/mui-rte#178]
Hi,
MUI v5 is available in an early alpha version. The peer dependency declaration to limit the support for MUI 4 only is reasonable.

So far, MUI v5 introduced smaller changes, which are not reflected in the current RTE version, such as removing a buttons color value "default" and or minor modification to how to define Grid flex behavior.

In summary, these changes are relatively minimal and not breaking the current RTE behavior significantly. For this reason, maybe an RTE@next deployment is possible with those changes made; otherwise, I have to do a separate deployment.

Thx!

**Comment by talisto** [comment]
MUI v5 is in beta now with a stable release coming soon (Q3 2021) so this will be needed shortly!

**Comment by arpitBhalla** [comment]
MUI v5 stable release done, please upgrade the package

**Comment by niuware** [comment]
@gurkerl83 @talisto @arpitBhalla  
Version `2.0.0` added compatibility with MUI (Material-UI v5). Check it [here](https://github.com/niuware/mui-rte/releases/tag/2.0.0).
