### ISSUE TITLE
Editor cannot receive focus when empty, and when populated, focuses in wrong place

### ISSUE THREAD

**Issue by caitecoll** [niuware/mui-rte#184]
## Checklist

- [X] This is not covered in the [repository examples](https://github.com/niuware/mui-rte/tree/master/examples).
- [X] I am using the package [latest version](https://github.com/niuware/mui-rte/releases/latest).
- [X] This is a bug report or an enhancement proposal.

## Description

There are two issues here, both related to keyboard focus on the text area: 

**Issue 1:** 
* When the editor is empty (like in the main [mui-rte CodeSandbox demo](https://codesandbox.io/s/mui-rte-basic-ypfdo?fontsize=14)), it's impossible for it to gain focus using the keyboard. 

**Issue 2:** 
* When the editor contains text, it is possible to focus into the editor using a keyboard, however it focuses at the beginning of the content rather than at the end.

## Steps to reproduce

1. Tab through toolbar buttons
2. Notice it's impossible to focus on the editor
3. Click on the editor and type in "aaa"
4. Use the keyboard to navigate through the toolbar buttons
5. Notice the editor can receive focus, but focus is at the beginning of the string rather than at the end of it.

**Comment by niuware** [comment]
This was fixed on [this release](https://github.com/niuware/mui-rte/releases/tag/1.25.0).

**Comment by tactycadmin** [comment]
Is there no way to focus on an empty text container with a mouse event? Seems like only the TAB key press is supported?

**Comment by niuware** [comment]
Do you mean with some synthetic mouse event? What will be the use case?

**Comment by niuware** [comment]
@tactycadmin This is fixed on version `1.26.0`.
