### ISSUE TITLE
Image size distorts rest of page

### ISSUE THREAD

**Issue by inform880** [niuware/mui-rte#186]
## Checklist

- [x] This is not covered in the [repository examples](https://github.com/niuware/mui-rte/tree/master/examples).
- [x] I am using the package [latest version](https://github.com/niuware/mui-rte/releases/latest).
- [x] This is a bug report or an enhancement proposal.

## Description

Hello!

This is my like, second bug report on GitHub ever, so please be patient. What I am finding is that images uploaded by the user can be any size they like, which is fine, but what I'm confused about that is how do I control the image size after the user posts? What's happening now is the image either squishes everything on the page to the side, or I cut the image off where I try to resize it. Currently it just scrolls the page horizontally, which is definitely not what I want.

I believe this is a feature request, but if anyone can point me to the right documentation or code example I would gladly appreciate it. You can see the behavior in production here, but requires google oauth redirect: https://thinkfloat.net/post/149

For those wary of that login, here's a GIF:
![2020-09-30 10 49 35](https://user-images.githubusercontent.com/6600519/94701472-afdd3c00-030a-11eb-935c-e84f06d308e6.gif)

**Comment by niuware** [comment]
So basically what you mean is, the image goes beyond the frame of the editor when no explicit `width` and `height` is set when inserting it?

**Comment by inform880** [comment]
I'm saying if I specify the width or height in the editor, it cuts off the image. Is there currently no way to resize the image or set a scroll on the editor?

**Comment by inform880** [comment]
I figured it out. I still think there should be some way of resizing the image, but the issue with this specifically is not related to that.
