### ISSUE TITLE
Is it possibile to use a plugin based on Draft-js

### ISSUE THREAD

**Issue by xipeter** [niuware/mui-rte#188]
I am adding the ability to be able to insert the emojis into the editor, there's already a plugin  - "draft-js-emoji-plugin" available, but it's for draft-js only,  if we can have the mui editor to be able to use that plugin, would be very helpful.

**Comment by niuware** [comment]
There is no support for `draft-js-plugins-editor`. You can check this [example](https://github.com/niuware/mui-rte/blob/master/examples/autocomplete/index.tsx) to know how to add emojis or stickers to the editor.
