### ISSUE TITLE
Can press enter after reaching max length

### ISSUE THREAD

**Issue by drxcheng** [niuware/mui-rte#189]
## Checklist

- [X] This is not covered in the [repository examples](https://github.com/niuware/mui-rte/tree/master/examples).
- [X] I am using the package [latest version](https://github.com/niuware/mui-rte/releases/latest).
- [X] This is a bug report or an enhancement proposal.

## Description

When I reach the maximum character limit, I can still type "enter", other characters are fine.

**Comment by niuware** [comment]
This was fixed on [this release](https://github.com/niuware/mui-rte/releases/tag/1.25.0)

**Comment by drxcheng** [comment]
thanks! I'll give a try.

**Comment by drxcheng** [comment]
it seems it isn't fixed.
