### ISSUE TITLE
Support for Draft JS plugins?

### ISSUE THREAD

**Issue by rasjonell** [niuware/mui-rte#19]
Hi again.

I wanted to add a custom draft-js [mention](https://www.draft-js-plugins.com/plugin/mention) plugin and realized that there is no option for that.

It would be really helpful to be able to pass `plugins` prop.

**Comment by niuware** [comment]
@rasjonell `MUIRichTextEditor` component is based on the *draft-js* `Editor` component, so I'm not sure I will be implementing the feature you are requesting at the moment. Thanks for your support.
