### ISSUE TITLE
Video is not working

### ISSUE THREAD

**Issue by mortoni** [niuware/mui-rte#199]
Hi guys,

Thanks for this amazing library, I am wondering if there is a specific way to add a video in the Editor. I am getting an error when I try to add a video on my local and on your demo:
https://codesandbox.io/s/mui-rte-basic-ypfdo?fontsize=14

Video url: https://www.youtube.com/watch?v=sjoepLlVL6o

<img width="677" alt="Screen Shot 2020-10-23 at 8 43 11 am" src="https://user-images.githubusercontent.com/7925408/96937922-9182ee80-150c-11eb-8afb-6032d1e2691a.png">

Could you please tell me what's wrong?

Note: I have tried vimeo and youtube videos, but none of them work.

**Comment by alanmortoni** [comment]
When you change the media from video to iframe it works, any idea when this issue will be fixed?

**Comment by niuware** [comment]
This feature works as expected, you need to add a valid URL video. This was never intended to work specifically with the URL you provide in your example. If you want to add videos from other services you would need to create your own component.
