### ISSUE TITLE
Control text during typing

### ISSUE THREAD

**Issue by MelqonyanG** [niuware/mui-rte#2]
While typing, you cannot control text until you click the Save button. It would be better to have an onChange function.

**Comment by niuware** [comment]
I have added the `onChange` property to the `MUIRichTextEditor` component. Check out the `README` or the `events` example for details on how to use it :)

**Comment by MelqonyanG** [comment]
> I have added the `onChange` property to the `MUIRichTextEditor` component. Check out the `README` or the `events` example for details on how to use it :)

Thank you very much for your support

**Comment by Harshjit-9600** [comment]
i've tried as it is in the readme file but that's not working ,can you give give me syntax for that @MelqonyanG
