### ISSUE TITLE
Request for examples

### ISSUE THREAD

**Issue by TrejGun** [niuware/mui-rte#200]
## Checklist

- [x] This is not covered in the [repository examples](https://github.com/niuware/mui-rte/tree/master/examples).
- [x] I am using the package [latest version](https://github.com/niuware/mui-rte/releases/latest).
- [x] This is a bug report or an enhancement proposal.

## Description

Hi guys! thanks a lot for awesome tool. I'm wotking with it for a couple of days and now have some questions to ask

Lets say i have custom button wich adds custom widget (card from examples) How can I remove this card if i don't need it any more. I mean I can add button for this in top right corner of card but how can I do this from markup perspective. Are there some methods for markup manipulations? may be in RichUtils?

**Comment by niuware** [comment]
Currently custom atomic blocks can only be removed by the `delete` key. Editing custom atomic blocks after inserted is not supported yet.

**Comment by TrejGun** [comment]
@niuware thanks for your response
its ok to remove and add block again if I want to edit it
but my initial request for example of block manipulation is still in place
