### ISSUE TITLE
Autofocus prevent mui-rte to be part of a form with other inouts

### ISSUE THREAD

**Issue by alanmortoni** [niuware/mui-rte#204]
## Checklist

- [ x] This is not covered in the [repository examples](https://github.com/niuware/mui-rte/tree/master/examples).
- [ x] I am using the package [latest version](https://github.com/niuware/mui-rte/releases/latest).
- [ x] This is a bug report or an enhancement proposal.

## Description

In a form, if start typing on mui-rte then I type in another text field, it keeps stealing the focus from my text field to mui-rte.

Would be nice if we can enable autofocus via api

**Comment by mortoni** [comment]
Sorry this issue has nothing to do with mui-rte. You can close it.
