### ISSUE TITLE
Screen goes blank when I highlight rte content and clear with backspace key

### ISSUE THREAD

**Issue by kayeew** [niuware/mui-rte#211]
Notice theres an issue when I enter some data into the rte component, highlight everything and try to clear with backspace key, my app went blank. Does someone know how to handle this? I have tried adding if statements to event and event.getCurrentContent() that comes from my onRTEChange function but still throwing this error below. i have also tried console logged event and event.getCurrentContent() but i cant pick out how to handle this error. Anyone any ideas how to handle this issue?

![image](https://user-images.githubusercontent.com/42571166/99611069-d81a2900-2a77-11eb-86bb-27e92ada7009.png)

```
const [value, setValue] = useState(values.comment || '')

const onRTEChange = event => {
    const content = JSON.stringify(convertToRaw(event.getCurrentContent()))
    setGuidelines(content)
}

<MUIRichTextEditor
  readOnly={disabled}
  id="rte-comment"
  label="Comment"
  controls={['numberList']}
  value={value}
  onChange={onRTEChange}
/>
```

**Comment by niuware** [comment]
Sorry I could not reproduce this problem. Are you using the latest version? Will close for now.
