### ISSUE TITLE
How simple way to save data to HTML?

### ISSUE THREAD

**Issue by albertolotz** [niuware/mui-rte#216]
## Checklist

- [ x ] This is not covered in the [repository examples](https://github.com/niuware/mui-rte/tree/master/examples).
- [ x ] I am using the package [latest version](https://github.com/niuware/mui-rte/releases/latest).
- [ ] This is a bug report or an enhancement proposal.

## Description

Hello,
How can I convert data that is text type to type ContentState?
I Need just convert a text to HTML when save. 

const save = (data: string) => {
  -->convert data  is here ???  
  console.log(stateToHTML(data));
  };

**Comment by webpct** [comment]
Any updates for this ? I have the same problem

**Comment by louiscklaw** [comment]
if i understand correctly.
it look like similar to the ticket #138  ...

**Comment by martinrojas** [comment]
There is a package 'draftjs-to-html' that can perform the conversion, but I think that there would be good util classes to have as part of this package. Call this from your onSave

`const parseToHtml = (value) => {
	const rawContentState = JSON.parse(value);
	const markup = draftToHtml(rawContentState);
	// console.log('[RTF] onChange:', markup);
	return markup;
};`

**Comment by albertolotz** [comment]
@martinrojas thank you a lot, your advice did help me.

With 3 lines bellow I did what I wanted

const rawText = // my Raw text;
const rawContentState = JSON.parse(rawText);
const markup = draftToHtml(rawContentState);
