### ISSUE TITLE
Compilation Error in Typescript React Project

### ISSUE THREAD

**Issue by lemorian** [niuware/mui-rte#22]
Hi,

I installed the module in my react typescript project and I am getting typescript error within the mui-rte source code.

![image](https://user-images.githubusercontent.com/11544422/65475878-bbe42180-de9e-11e9-9055-c642c8a966aa.png)

Below is my tsconfig.

`{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react",
    "noImplicitAny": false
  },
  "include": [
    "src"
  ]
}
`

**Comment by niuware** [comment]
Hi @lemorian Thanks for using this component. I have tried to replicate your problem with no success, even setting the `strictNullChecks` flag on. Which version of Typescript are you currently using?

**Comment by lemorian** [comment]
I am using "typescript": "3.5.3".

**Comment by lemorian** [comment]
Your comment got me thinking, so tried setting "strictNullChecks":false explicitly, and that seems to fix the issue.
Thank you for your quick response.
