### ISSUE TITLE
Yarn tsc: error TS2345

### ISSUE THREAD

**Issue by darklongnightt** [niuware/mui-rte#230]
## Checklist

- [x] This is not covered in the [repository examples](https://github.com/niuware/mui-rte/tree/master/examples).
- [x] I am using the package [latest version](https://github.com/niuware/mui-rte/releases/latest).
- [x] This is a bug report or an enhancement proposal.

## Description

I am encountering the following lint errors when running yarn tsc in my typescript project that imports MUIRichTextEditor.

```
node_modules/mui-rte/src/MUIRichTextEditor.tsx:1017:32 - error TS2345: Argument of type 'KeyboardEvent<{}>' is not assignable to parameter of type 'SyntheticKeyboardEvent'.
  Property 'code' is missing in type 'KeyboardEvent<{}>' but required in type 'SyntheticKeyboardEvent'.

1017         if (hasCommandModifier(e) && props.keyCommands) {
                                    ~

  node_modules/@types/react-router/node_modules/@types/react/index.d.ts:1214:9
    1214         code: string;
                 ~~~~
    'code' is declared here.

node_modules/mui-rte/src/MUIRichTextEditor.tsx:1029:49 - error TS2345: Argument of type 'KeyboardEvent<{}>' is not assignable to parameter of type 'SyntheticKeyboardEvent'.

1029         const keyBinding = getDefaultKeyBinding(e)
                                                     ~


Found 2 errors.
```

**Comment by Faey2222** [comment]
I just got exactly the same error... :(

**Comment by Uniphix** [comment]
I got this same error too...

**Comment by RedIronLabs** [comment]
me too

**Comment by darklongnightt** [comment]
Update: this was resolved by updating the type definitions in packages.json to a newer version, I am currently using the following version that works:
"@types/react": "17.0.1"
"eslint": "7.19.0"
