### ISSUE TITLE
Integration with React hook form

### ISSUE THREAD

**Issue by dashty94** [niuware/mui-rte#234]
## Checklist

- [ ] This is not covered in the [repository examples](https://github.com/niuware/mui-rte/tree/master/examples).
- [ ] I am using the package [latest version](https://github.com/niuware/mui-rte/releases/latest).
- [ ] This is a bug report or an enhancement proposal.

## Description

How do you integrate it with React hook Form? I can't get the value of the editor and pass it to the form

**Comment by chemiadel** [comment]
Wrap it on Controller, Only way to get data is onSave so you need to save it by refs and use onChange of controller under save event:

<Controller
  control={control}
  name="editor"
  render={(
    { onChange }
  ) => (
          <MUIRichTextEditor
                ref={ref}
                controls={["undo", "redo","title", "bold", "italic", "highlight", "link", "media", "numberList", "bulletList", "quote"]}
                label="Type something here..."
                onChange={()=>ref.current.save()}
                onSave={data=>onChange(data)}
              />
  )}
/>
