### ISSUE TITLE
production build fails 

### ISSUE THREAD

**Issue by Igor2122** [niuware/mui-rte#238]
## Checklist

- [x] This is not covered in the [repository examples](https://github.com/niuware/mui-rte/tree/master/examples).
- [x] I am using the package [latest version](https://github.com/niuware/mui-rte/releases/latest).
- [x] This is a bug report or an enhancement proposal.

## During production build, getting below error 

``./node_modules/mui-rte/src/MUIRichTextEditor.tsx:1017:32
Type error: Argument of type 'KeyboardEvent<{}>' is not assignable to parameter of type 'SyntheticKeyboardEvent'.
  Property 'code' is missing in type 'React.KeyboardEvent<{}>' but required in type 'import("/Users/igorpavlneko/Desktop/prj/pexpats_f_e/node_modules/@types/react-dom/node_modules/@types/react/index").KeyboardEvent<{}>'.

  1015 | 
  1016 |     const keyBindingFn = (e: React.KeyboardEvent<{}>): string | null => {
> 1017 |         if (hasCommandModifier(e) && props.keyCommands) {
       |                                ^
  1018 |             const comm = props.keyCommands.find(comm => comm.key === e.keyCode)
  1019 |             if (comm) {
  1020 |                 return comm.name
error Command failed with exit code 1.
```

**Comment by vilanz** [comment]
There's a workaround in https://github.com/niuware/mui-rte/issues/230

But the proper solution would be https://github.com/niuware/mui-rte/issues/206, which was closed for some reason

**Comment by TrejGun** [comment]
it was cloed because this repository seems to be dead now and our company forked it and going to maintain
for example we have fixed nested lists

**Comment by niuware** [comment]
@vilanz This is fixed in version [1.28.0](https://github.com/niuware/mui-rte/releases/tag/1.28.0).
