### ISSUE TITLE
Overwrite MUIRichTextEditor default image control

### ISSUE THREAD

**Issue by thngdude** [niuware/mui-rte#272]
## Checklist

- [no] This is not covered in the [repository examples](https://github.com/niuware/mui-rte/tree/master/examples).
- [yes] I am using the package [latest version](https://github.com/niuware/mui-rte/releases/latest).
- [no] This is a bug report or an enhancement proposal.

## Description

The readme says we can use the "MUIRichTextEditor default image control for further edition" after inserting an image block into the editor. Is it possible to overwrite this default image control popover? 

On a related note, how to you define a custom "controllers to edit blocks that are already in the Editor?

**Comment by niuware** [comment]
@thngdude Both features you mention are currently not yet supported.

**Comment by thngdude** [comment]
Just wanted to add that if you are in a similar situation as I am, you can use the `draftEditorProps` prop on the `MUIRichTextEditor` component to override default blocks for different block types, including Media. So, you can completely replace the default Media components for URL embedded components.

Edit: Forgot to add you can define the custom blocks using the `blockRendererFn` object under `draftEditorProps`, which is a prop passed to the draft-js Editor component.
