### ISSUE TITLE
Non-unique IDs when using more than 1 RTE

### ISSUE THREAD

**Issue by hamdi-karim** [niuware/mui-rte#273]
## Checklist

- [x] This is not covered in the [repository examples](https://github.com/niuware/mui-rte/tree/master/examples).
- [x] I am using the package [latest version](https://github.com/niuware/mui-rte/releases/latest).
- [x] This is a bug report or an enhancement proposal.

## Description
I'm using 6 mui-rte components in my screen. 
Is there a way to get rid of this warning (screenshot), it seems that it's generating the same ID for different components.
![image](https://user-images.githubusercontent.com/34784654/135843645-629411b0-76ea-464a-bda0-e95dcce6bf85.png)
@niuware  Could you please look at this ?
Thanks

**Comment by niuware** [comment]
Seems like you are not setting the `id` property for the `MUIRichTextEditor` component.
