### ISSUE TITLE
Vite:import-analysis : Failed to resolve entry for package "mui-rte"

### ISSUE THREAD

**Issue by dailenisgonzalez** [niuware/mui-rte#275]
## Checklist

- [ ] This is not covered in the [repository examples](https://github.com/niuware/mui-rte/tree/master/examples).
- [ ] I am using the package [latest version](https://github.com/niuware/mui-rte/releases/latest).
- [ ] This is a bug report or an enhancement proposal.

## Description

When I run the npm start the app throw this error: 

node_modules/vite/dist/node/chunks/dep-36bf480c.js:43807:10: error: [plugin: vite:dep-scan] Failed to resolve entry for package "mui-rte". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "mui-rte". The package may have incorrect main/module/exports specified in its package.json.
43807 │ throw new Error(`Failed to resolve entry for package "${id}". `

I check the node package.json from "mui-rte" in node module and in the main the route to index.js is wrong because is pointing to dist if I remove dist from there it's works.

<img width="1280" alt="Screen Shot 2021-10-05 at 10 12 04" src="https://user-images.githubusercontent.com/87542019/136061640-45e931ff-babd-47f8-ac71-10a062e9ecb1.png">

<img width="880" alt="Screen Shot 2021-10-05 at 10 05 09" src="https://user-images.githubusercontent.com/87542019/136060646-58cf7d25-3b99-4d01-b7b4-abfdf6c27d14.png">
``

**Comment by niuware** [comment]
@dailenisgonzalez Thanks for the bug report, version [2.0.1](https://github.com/niuware/mui-rte/releases/tag/2.0.1) should fix this. Could you give it a try?

**Comment by dailenisgonzalez** [comment]
@niuware  It is working now , awesome :) , thanks
