### ISSUE TITLE
Update version of draftJS to 0.11.1

### ISSUE THREAD

**Issue by sanchitd5** [niuware/mui-rte#28]
Editor is giving warning to update DraftJS on react as 'componentWillUpdate' has been renamed in the react version 17.x and is not recommended for use.

**Comment by niuware** [comment]
@sanchitd5 Thanks for the heads up. This update is definitely planned for a coming version.

**Comment by niuware** [comment]
The release 1.4.0 includes the latest version of 'draft-js' so I am closing this issue. Please check it out.
