### ISSUE TITLE
Problem with selecting inline styles when no text is selected

### ISSUE THREAD

**Issue by maattss** [niuware/mui-rte#3]
When trying to select an inline style (i.e. bold and italic) without any text selected, button is not marked. I'm unable to figure out what's causing this. This does not appear to be a problem in Draft.js demo on their official site. Are you able to help or point me in the right direction?

**Comment by niuware** [comment]
@maattss Thanks for your comment. I have verified the issue and will solve it soon.

**Comment by niuware** [comment]
@maattss Fixed on version 1.0.15 :)

**Comment by maattss** [comment]
> @maattss Fixed on version 1.0.16 :)

Thanks for your support, appreciate it!
