### ISSUE TITLE
Feature Request: image resize

### ISSUE THREAD

**Issue by sanchitd5** [niuware/mui-rte#30]
Just wondering we a feature can be added to resize image in the editor itself, something similar to 'https://www.draft-js-plugins.com/plugin/resizeable'.

**Comment by niuware** [comment]
@sanchitd5 Thanks for your comment. Currently I have other improvements I want to implement, and then I could see the possibility to add this one. For now, you can change the size of the image by setting the width and height in the 'image' control popover.
