### ISSUE TITLE
ReferenceError: global is not defined

### ISSUE THREAD

**Issue by xrei** [niuware/mui-rte#309]
## Checklist

- [x] This is not covered in the [repository examples](https://github.com/niuware/mui-rte/tree/master/examples).
- [x] I am using the package [latest version](https://github.com/niuware/mui-rte/releases/latest).
- [x] This is a bug report or an enhancement proposal.

## Description

Trying to import this module, installed all deps, but have following error

<img width="620" alt="image" src="https://user-images.githubusercontent.com/9521710/166572352-d45021e4-3d6f-446a-8826-20a5c9301a7e.png">

**Comment by xrei** [comment]
This fixed the issue: https://www.npmjs.com/package/@rollup/plugin-commonjs

**Comment by aprilmintacpineda** [comment]
On your `index.html`, add the following on the head:

```html
<script>
  var global = window;
</script>
```
