### ISSUE TITLE
Updating of content doesn't rerender

### ISSUE THREAD

**Issue by fscholze** [niuware/mui-rte#31]
Hey, that component is quite nice. 
There is just one thing, I don't get:
I download some data and want to show it in your component. The format is ok. But when render my view the first time, I have no data, so the default value is empty. When I am getting the data and update my state, my view is rerender (as it should) but your component is still empty. Do you know how I could fix it?

**Comment by niuware** [comment]
@fscholze Thanks for using the component.
I believe the property name is a bit confusing as it is intended as a default value only. If you want to update the value after, please check out this solution: https://github.com/niuware/mui-rte/issues/17#issuecomment-531064920
Hopes this help you out for now.

**Comment by fscholze** [comment]
Thank you, that works!
