### ISSUE TITLE
Unable to place the toolbar below the textfield

### ISSUE THREAD

**Issue by Zabi-Progton** [niuware/mui-rte#32]
I have been trying to change the styling of the toolbar but failing to pull it down below the textfield, how can I achieve this.

**Comment by niuware** [comment]
@Zabi-Progton Thanks for using the component. Have you tried this: https://github.com/niuware/mui-rte/issues/18#issuecomment-531055798
Hope it helps.

**Comment by Zabi-Progton** [comment]
Thanks for such a quick and adequate reply Good sir.
