### ISSUE TITLE
Chrome console warning [...merges existing Range and the specified Range was removed]

### ISSUE THREAD

**Issue by IdkMan2** [niuware/mui-rte#35]
Stack trace:
![image](https://user-images.githubusercontent.com/23725071/66651593-b1ae7b00-ec33-11e9-8a9f-b2b736c0375b.png)

**Comment by niuware** [comment]
@IdkMan2 I have release a fix on version `1.5.2`. Hopes this solves it :)

**Comment by IdkMan2** [comment]
Many thanks for fast response and fix.
