### ISSUE TITLE
Unable to insert text

### ISSUE THREAD

**Issue by paulsergeant** [niuware/mui-rte#38]
Is there functionally for inserting text via a button push?

**Comment by niuware** [comment]
@paulsergeant Thanks for using this component.
Does creating a [custom block control](https://github.com/niuware/mui-rte/blob/master/examples/custom-controls/index.tsx) help you out?

**Comment by paulsergeant** [comment]
At the moment I am able to insert text using Modifier.insertText() from the draft-js library. However when I use it with the mui-rte, when I click back into the text box the inserted text disappears and the editorState updates.

When I used the same function with the draft js Editor, the text stayed where it was supposed to.

**Comment by paulsergeant** [comment]
`
import React, { useState } from 'react';
import Button from '@material-ui/core/Button';
import { createMuiTheme, MuiThemeProvider } from '@material-ui/core/styles';
import MUIRichTextEditor from 'mui-rte';
import { Editor, EditorState, Modifier } from 'draft-js';
import { stateToHTML } from 'draft-js-export-html';

const defaultTheme = createMuiTheme();

Object.assign(defaultTheme, {
  overrides: {
    MUIRichTextEditor: {
      root: {
        marginTop: 20,
        width: '80%'
      },
      editor: {
        borderBottom: '1px solid gray'
      }
    }
  }
});

export default () => {
  const [editorState, setEditorState] = useState(EditorState.createEmpty());

  const handleButtonClick = () => {
    let contentState = editorState.getCurrentContent();
    const selectionState = editorState.getSelection();
    const contentStateWithEntity = contentState.createEntity(
      'MY_ENTITY_TYPE',
      'IMMUTABLE'
    );
    const entityKey = contentStateWithEntity.getLastCreatedEntityKey();
    contentState = Modifier.insertText(
      contentState,
      selectionState,
      '*** Inserted Text ***',
      null,
      entityKey
    );

    let newState = EditorState.push(
      editorState,
      contentState,
      'insert-characters',
      null,
      entityKey
    );

    if (!newState.getCurrentContent().equals(editorState.getCurrentContent())) {
      const sel = newState.getSelection();
      const updatedSelection = sel.merge({
        anchorOffset: sel.getAnchorOffset() + 1,
        focusOffset: sel.getAnchorOffset() + 1
      });
      newState = EditorState.forceSelection(newState, updatedSelection);
    }
    setEditorState(newState);
  };

  const getHTML = () => {
    const content = editorState.getCurrentContent();
    const html = stateToHTML(content);

    return html;
  };

  return (
    <div>
      <MuiThemeProvider theme={defaultTheme}>
        <MUIRichTextEditor
          label='Type something here...'
          onChange={editorState => setEditorState(editorState)}
          editorState={editorState}
        />
        <div
          dangerouslySetInnerHTML={{
            __html: getHTML()
          }}
        />
      </MuiThemeProvider>
      <Button onClick={() => handleButtonClick()}>Button</Button>
    </div>
  );
};
`

**Comment by paulsergeant** [comment]
`
import React, { useState } from 'react';
import Button from '@material-ui/core/Button';
import { createMuiTheme, MuiThemeProvider } from '@material-ui/core/styles';
import MUIRichTextEditor from 'mui-rte';
import { Editor, EditorState, Modifier } from 'draft-js';
import { stateToHTML } from 'draft-js-export-html';

const defaultTheme = createMuiTheme();

Object.assign(defaultTheme, {
  overrides: {
    MUIRichTextEditor: {
      root: {
        marginTop: 20,
        width: '80%'
      },
      editor: {
        borderBottom: '1px solid gray'
      }
    }
  }
});

export default () => {
  const [editorState, setEditorState] = useState(EditorState.createEmpty());

  const handleButtonClick = () => {
    let contentState = editorState.getCurrentContent();
    const selectionState = editorState.getSelection();
    const contentStateWithEntity = contentState.createEntity(
      'MY_ENTITY_TYPE',
      'IMMUTABLE'
    );
    const entityKey = contentStateWithEntity.getLastCreatedEntityKey();
    contentState = Modifier.insertText(
      contentState,
      selectionState,
      '*** Inserted Text ***',
      null,
      entityKey
    );

    let newState = EditorState.push(
      editorState,
      contentState,
      'insert-characters',
      null,
      entityKey
    );

    if (!newState.getCurrentContent().equals(editorState.getCurrentContent())) {
      const sel = newState.getSelection();
      const updatedSelection = sel.merge({
        anchorOffset: sel.getAnchorOffset() + 1,
        focusOffset: sel.getAnchorOffset() + 1
      });
      newState = EditorState.forceSelection(newState, updatedSelection);
    }
    setEditorState(newState);
  };

  const getHTML = () => {
    const content = editorState.getCurrentContent();
    const html = stateToHTML(content);

    return html;
  };

  return (
    <div>
      <MuiThemeProvider theme={defaultTheme}>
        <Editor
          label='Type something here...'
          onChange={editorState => setEditorState(editorState)}
          editorState={editorState}
        />
        <div
          dangerouslySetInnerHTML={{
            __html: getHTML()
          }}
        />
      </MuiThemeProvider>
      <Button onClick={() => handleButtonClick()}>Button</Button>
    </div>
  );
};

`

**Comment by paulsergeant** [comment]
Swapping <Editor /> for <MUIRichTextEditor /> and clicking the button shows the difference.

**Comment by niuware** [comment]
This component is based on `draft-js` but you cannot use its API directly. The `MUIRichTextEditor` API is [here](https://github.com/niuware/mui-rte/blob/master/README.md). The way you are trying to modify the text is not possible but you can set the editor `ContentState` by setting the `value` property as shown [here](https://github.com/niuware/mui-rte/blob/master/examples/reset-value/index.tsx) or by creating a custom control.
