### ISSUE TITLE
make editor area fit 100% height

### ISSUE THREAD

**Issue by kanekv** [niuware/mui-rte#40]
I want to force editor to fit 100% of the available height. When I add more lines it pushes height over that limit. How is it possible to force it to stay within the limit?

**Comment by niuware** [comment]
@kanekv Thanks for using the component. Please take a look to the [theme](https://github.com/niuware/mui-rte/blob/master/examples/theme/index.tsx) example. Basically you will need to override the `editor` style as follows:

```js
export const defaultTheme: Theme = createMuiTheme({
    palette: {
        primary: {
            main: "#000000"
        }
    }
})

Object.assign(defaultTheme, {
    overrides: {
        MUIRichTextEditor: {
            editor: {
                height: "100vh",
                maxHeight: "100vh",
                overflow: "auto"
            }
        }
    }
})
```

Hopes this help you out!

**Comment by acabreragnz** [comment]
@niuware Thank you for this awesome component!

I'm using the solution you provided, but I had some issues.
It seems to be that the label is using an extra row, then when you press the editor, the placeholder of the label is removed and the editor reduce its overall height in one line. It is like a weird effect, because everything on the page (that is below) moves up. 

How can I solve it?

Thank you in advance!

**Comment by niuware** [comment]
Hi @acabreragnz Thanks for your comment. I found a bug related with this and now should be fixed on version `1.16.1`. Hope it helps you out.

**Comment by acabreragnz** [comment]
Thank you @niuware !

**Comment by mosofsky** [comment]
I've upgraded to "MUI v5" and found out the syntax seems to have changed such that `overrides` has been changed to `components`:

```
const theme = createTheme({
    palette: abcPalette,
    components: {
        // @ts-ignore
        MUIRichTextEditor: {
            root: {
                width: "100%",
            },
            editor: {
                height: "100vh",
                maxHeight: "100vh",
                overflow: "auto",
            },
        },
    },
});
```

Source: https://mui.com/guides/migration-v4/#theme-structure

The code above worked for these versions:

* "mui-rte": "2.0.1" 
* "@mui/material": "^5.5.3"
