### ISSUE TITLE
How to check if MUIRichTextEditor is empty?

### ISSUE THREAD

**Issue by Abinaskarki** [niuware/mui-rte#44]
Hi @niuware , thank you for your wonderful rich text editor package. I would like to know how do I check if MUIRichTextEditor is empty or not, because even if it is empty, there is some default object already created there.

**Comment by niuware** [comment]
@Abinaskarki thanks for using the package. Did you try using the `hasText` method of the `ContentState`? 

```js
const change = (state) => {
    if (!state.getCurrentContent().hasText()) {
        console.log("Empty")
    }
}

const App = () => {
    return (
        <MUIRichTextEditor 
            onChange={change}
        />
    )
}
```

Find a complete events example [here](https://github.com/niuware/mui-rte/blob/master/examples/events/index.tsx). 

Hope this helps!
