### ISSUE TITLE
Compilation Error in Typescript React Project

### ISSUE THREAD

**Issue by mbadev62** [niuware/mui-rte#46]
Hi, 
when I try compile project with `"noUnusedParameters": true,`, I get error in 
`ERROR in ..\node_modules\mui-rte\src\MUIRichTextEditor.tsx(178,62)` 
`TS6133: 'contentState' is declared but its value is never read.`

**Comment by niuware** [comment]
@mbadev62 Thanks for the heads up, this is fixed on version `1.8.2`.

**Comment by mbadev62** [comment]
Thanks for quick fix!
