### ISSUE TITLE
buttons in the toolbar are forced to be IconButton

### ISSUE THREAD

**Issue by kanekv** [niuware/mui-rte#47]
Is it possible to override IconButton in the toolbar? May be CustomControl should propagate all of the props to IconButton so we can replace component in there (I would like to be able to insert something completely custom in there).

**Comment by niuware** [comment]
@kanekv Thanks for using the package. The idea is useful so I implemented it on version `1.9.0`. You can check the updated custom controls [example](https://github.com/niuware/mui-rte/blob/master/examples/custom-controls/index.tsx) and the updated documentation for more details on how to use it.
Hopes it helps!

**Comment by kanekv** [comment]
Awesome! Thanks for quick reply!
