### ISSUE TITLE
How to use Editor.forceSelection() in this library, can you please share an example?

### ISSUE THREAD

**Issue by Zabi-Progton** [niuware/mui-rte#51]
I have been trying to update the value of my MUIRTE using the following code.
```
 const change = (state) => {
    const currentSelection = state.getSelection()
    const content_state = state.getCurrentContent()
    const newEditorState = EditorState.forceSelection(content_state, currentSelection)
    const final = JSON.stringify(convertToRaw(newEditorState))
    setEditorState(final)
  }
```

But I am unable to do so and I am getting this error in the console 

`Uncaught TypeError: editorState.getImmutable is not a function`

I am using the forceSelection because it helps in removing the cursor reset error in the MUIRichTextEditor component. As answered in this post: [https://stackoverflow.com/questions/43868815/how-to-stop-draftjs-cursor-jumping-to-beginning-of-text](url)

Please help!

**Comment by niuware** [comment]
Currently is not possible to change the selection (or modifying the editor state) externally. This may change in future versions.

**Comment by Zabi-Progton** [comment]
So how do I make the MUIEditor a controlled component?
