### ISSUE TITLE
onChange restarting the cursor from the beginning

### ISSUE THREAD

**Issue by Abinaskarki** [niuware/mui-rte#52]
Hi @niuware, I have been using mui-rte in a Material UI dialog box. When I start to write the cursor is at the beginning, but when I write few words, then, the cursor again moves to the beginning. Therefore, I have to constantly move the cursor to write a sentence. I think onChange method is creating a problem, however, I cannot figure out what is causing the problem? Your help is highly appreciated.

Code:
```
const [post, setPost] = useState({
  content: '',
  answer_errors: {},
  open: false,
  errors: null
});

const handleChange = prop => event => {
  setPost({
    ...post,
    [prop]: JSON.stringify(convertToRaw(event.getCurrentContent()))
  });
};

<MUIRichTextEditor
  label="Write your aswer..."
  controls={[
    'bold',
    'italic',
    'underline',
    'highlight',
    'link',
    'media',
    'numberList',
    'bulletList',
    'quote'
  ]}
  inlineToolbar={true}
  onChange={handleChange('content')}
  value={post.content}
/>;

```

**Comment by niuware** [comment]
Hi @Abinaskarki, every time you change the `value` property you are actually resetting the editor. If you need to get the content of the editor on every change, you may use the `onChange` property but there is no need to assign the `value` again as the state of the component has been already updated internally. 

Hope this helps you :)

**Comment by Abinaskarki** [comment]
Hi @niuware, thank you for your response. If I don't have onChange property then, how would I access the content inside MUITextEditor when a button is clicked?

**Comment by niuware** [comment]
If I understand correctly, you have some choices:
1. You can keep updating the state of your own component using the `MUIRichTextEditor` component `onChange` property, but there is no need to set the `value` property again. (Use `value` property only when you want to load some default content).

2. If you just want to get the last state of the editor, you can trigger the `save` event by reference as shown [here](https://github.com/niuware/mui-rte/blob/master/examples/ref-save/index.tsx).

Does this helps you out?

**Comment by Abinaskarki** [comment]
Hi @niuware, sorry for the confusion. What I want to do is basically I will write something on a MUITextEditor and I have a button which should get the data written in MUITextEditor when clicked and do something. The only problem is that since I am not using onChange then, the content value in state is not updated and i am getting content from state. Is there another way to get text inside the MUITextEditor?

here is my code for the button;
```
const handleSubmit = () => {
  const { content } = post;
  const answerData = {
    content,
    questionId: props.questionId
  };
  const { answer_errors, valid } = validatePostAnswer(answerData);
  setPost({ ...post, answer_errors });

  if (!valid) {
    return;
  }
  props.postAnswer(answerData);
};

<Button
color="secondary"
variant="outlined"
className="w-1/4"
onClick={handleSubmit}
disabled={loading}
>
Post
</Button>
```

**Comment by niuware** [comment]
In that case, what about doing something like this:

```js
const [post, setPost] = useState({
    content: {},
    answer_errors: {},
    open: false,
    errors: null
});

const handleChange = prop => event => {
    setPost({
        ...post,
        [prop]: event
    });
};

const handleSubmit = () => {
    const { content } = post;
    const answerData = {
        content: JSON.stringify(convertToRaw(content.getCurrentContent())),
        questionId: props.questionId
    };
    props.postAnswer(answerData);
};
```
```jsx
<Button
    color="secondary"
    variant="outlined"
    className="w-1/4"
    onClick={handleSubmit}
    disabled={loading}
>
    Post
</Button>

<MUIRichTextEditor
    label="Write your aswer..."
    controls={[
        'bold',
        'italic',
        'underline',
        'highlight',
        'link',
        'media',
        'numberList',
        'bulletList',
        'quote'
    ]}
    inlineToolbar={true}
    onChange={handleChange('content')}
/>;
```

**Comment by Abinaskarki** [comment]
Thank you. However, it gave me an error. But, I think i figured out the solution. Now, I don't know how to check if 'data' in handleSave is empty or not because I don't want to post anything empty. 

Code:
```
  const [post, setPost] = useState({
    content: {},
    answer_errors: {},
    open: false,
    errors: null
  });
  const ref = useRef();
const handleSave = (data: string) => {
    const answerData = { content: data, questionId: props.questionId };

    const { answer_errors, valid } = validatePostAnswer(answerData.content);
    setPost({ ...post, answer_errors });

    if (!valid) {
      return;
    }
    props.postAnswer(answerData);
  };

  const handleSubmit = () => {
    ref.current.save();
  };
<MUIRichTextEditor
              label="Write your aswer..."
              onSave={handleSave}
              ref={ref}
              controls={[
                'bold',
                'italic',
                'underline',
                'highlight',
                'link',
                'media',
                'numberList',
                'bulletList',
                'quote'
              ]}
              inlineToolbar={true}
            />
```
This works perfectly. But, i don't know how to check empty on data of handleSave.

**Comment by niuware** [comment]
Just convert it back to a `ContentState` object: 
```js
const handleSave = (data: string) => {
    const content = convertFromRaw(JSON.parse(data))
    if (!content.hasText()) {
        console.log("empty")
    }
}
```

**Comment by Abinaskarki** [comment]
perfect. Thank you so much.

**Comment by helloncanella** [comment]
@niuware, you are right. If you don't change the `value` prop, the component isn't reset.

But here a suggestion: replace the name of `value` prop to `defaultValue`, to make it clear it is necessary to assign value only once.

Or at least, make available a `defaultValue` in the API.

**Comment by niuware** [comment]
> @niuware, you are right. If you don't change the `value` prop, the component isn't reset.
> 
> But here a suggestion: replace the name of `value` prop to `defaultValue`, to make it clear it is necessary to assign value only once.
> 
> Or at least, make available a `defaultValue` in the API.

Thanks @helloncanella, I will take this in mind for next version.

**Comment by efikuta** [comment]
Another Solution is using ref with onBlur to raise the save Event.
In this solution we making the text editor semi - controlled component, which handled it`s own state.

An Example:
`
const textEditorRef = useRef();
const [bodyHTML, setBodyHTML] = useState('');

const contentHTML = convertFromHTML(bodyHTML);
const stateHtml = ContentState.createFromBlockArray(
  contentHTML.contentBlocks,
  contentHTML.entityMap
);

const handleSave = (data) => {
    const content = convertFromRaw(JSON.parse(data))
    if (!content.hasText()) {
          console.log("empty")
    }
   setBodyHTML(stateToHTML(content));
}

<MUIRichTextEditor
                  ref={textEditorRef}
                  inlineToolbar={true}
                  defaultValue={JSON.stringify(convertToRaw(stateHtml))}
                  onSave={handleSave}
                  onBlur={() => { textEditorRef.current.save(); }}
                />

`
