### ISSUE TITLE
editor doesn't get focus on tab

### ISSUE THREAD

**Issue by kanekv** [niuware/mui-rte#55]
How to make editor receive focus on tab?

**Comment by kanekv** [comment]
Should component expose `handleFocus`?

**Comment by kanekv** [comment]
Submitted #56 in case you think it should work that way.

**Comment by niuware** [comment]
Hi @kanekv Could you make the pull request to `development` branch instead of `master`? Thank you.

**Comment by kanekv** [comment]
@niuware also, may be it should expose `editorRef` so it's possible to access Editor directly?

**Comment by kanekv** [comment]
I've submitted PR against development too.
