### ISSUE TITLE
Support server render

### ISSUE THREAD

**Issue by minhna** [niuware/mui-rte#61]
I use `readOnly` prop to display contents but it does not show up in server render.
Did I miss something? Please help. SEO is very important to us.

**Comment by niuware** [comment]
@minhna Do you mean when you set the `value` and `readOnly` properties the content is not showing up? I have tried SSR (with `Next.js` for fast testing) and the rendering is working as expected.

**Comment by niuware** [comment]
@minhna Thanks for using the component. I have released version `1.9.3` which fixes this situation. Let me know if it helps you out.

**Comment by minhna** [comment]
I'm using Meteor 1.8.2 and version 1.9.3 works perfectly with server rendering.
Thank you very much.
