### ISSUE TITLE
Small toolbar buttons

### ISSUE THREAD

**Issue by DesignyourCode** [niuware/mui-rte#68]
Is there a way to set the toolbar button as small using the Material UI `size` attribute?

**Comment by niuware** [comment]
@DesignyourCode Currently there is no property to set the size of the `IconButton`. I will add it on a next release.

**Comment by DesignyourCode** [comment]
Brilliant, thank you

**Comment by niuware** [comment]
This is added on version 1.11.0

**Comment by DesignyourCode** [comment]
Amazing, thank you

**Comment by niuware** [comment]
@DesignyourCode Are you setting the `toolbarButtonSize` property?

**Comment by DesignyourCode** [comment]
Sorry yes I am setting it, but it's not shrinking the icons at all.

**Comment by niuware** [comment]
The default component for a `ToolbarButton` is an `IconButton`, so the *small* size is the one provided by `material-ui` which basically just removes the padding from the `IconButton`. You can still use custom toolbar button components if you require a smaller size.
