### ISSUE TITLE
@material-ui/core dependency version

### ISSUE THREAD

**Issue by llamamoray** [niuware/mui-rte#71]
I'm currently using version 3.9.2 of @material-ui/core which the package.json of the latest version of this library suggests should be compatible. However I get the error:

`Module not found: Can't resolve '@material-ui/core/ButtonGroup' in '/mnt/c/git/hivemind.on-demand.web/node_modules/mui-rte/dist'` 

What version of this library would be compatible with 3.x of @material-ui/core?

**Comment by niuware** [comment]
@llamamoray From `mui-rte` version 1.6.1 I added the `ButtonGroup` control which is only available from `material-ui` versions 4.1.x; sorry for the incorrect package version ranges. I will fix the `package.json` file on the next release, but it is most likely I would drop compatibility for material-ui versions lower than that.

**Comment by niuware** [comment]
The compatibility with version 3.x notes have been deleted from version 1.12.0. I think it is possible to make it still work on versions 3.x, but I would need to make some further changes.
