### ISSUE TITLE
How to set a maxlength property for this editor ?

### ISSUE THREAD

**Issue by miguelangeltorresfp** [niuware/mui-rte#73]
I found this answer related to draft.js but I don't know if it would be possible to do something similar with mui-rte.

[How to limit Max Length of Draft js](https://stackoverflow.com/questions/46044251/how-to-limit-max-length-of-draft-js)

**Comment by niuware** [comment]
Hi @miguelangeltorresfp, with the link you sent, what about disabling the input when you reach a limit?

In this example when the user writes 10 characters, the input will be disabled. The only downside is that you will need show another button to re-enable the input once the limit is reached as you won’t be able to modify the content of the editor anymore.

Anyways the `max-length` could be a useful feature so I will probably add it in a next release. 

```typescript
const [readOnly, setReadOnly] = useState(false)

...

return (
    <MUIRichTextEditor 
        onChange={(editorState) => {
            const length = editorState.getCurrentContent().getPlainText('').length
            if (length >= 10) {
                setReadOnly(true)
            }
        }}
        readOnly={readOnly}
    />
)
```

**Comment by niuware** [comment]
This feature was added in version `1.14.0`
