### ISSUE TITLE
Additional header/title styles

### ISSUE THREAD

**Issue by mkwu** [niuware/mui-rte#74]
the Title control ultimately maps to a H2 tag if I convert the content to html. How does one add additional header tags.  I tried creating a custom block, but there doesn't seem to be a way to specify the style for something like draft-js-export-html to render additional header tags. Everything comes out as a paragraph tag.

eg:

```
<MUIRichTextEditor
     controls={["header-one"]}
     customControls={[
          {
                name: "header-one",
                type: "block",
                icon: <TitleIcon />,
                style: 'header-one',
                blockWrapper: <h1/>
          }                            
/>

```

**Comment by niuware** [comment]
@mkwu The `draft-js-export-html` package that you mention expects a `ContentState` object which you can access via the `onSave` or `onChange` properties. Just provide the `MUIRichTextEditor` output as an input to the package you use to convert to HTML.

Hope this helps :)

**Comment by SerbanCarjan** [comment]
@niuware sorry to resurrect this: `stateToHtml` from `draft-js-export-html` expects a `ContentState` object. Any suggestions on how to get from the stringified rawContentState that is exposed at `onSave` and `onChange` to a `ContentState` object?

**Comment by niuware** [comment]
@SerbanCarjan Maybe you can check [this](https://github.com/niuware/mui-rte/blob/master/examples/load-html/index.tsx) example

**Comment by SerbanCarjan** [comment]
@niuware it helped in a way, but I also went looking in the mui-rte source code, to check how it converts the `defaultValue` string internally. Thanks!
