### ISSUE TITLE
Problem with cursor

### ISSUE THREAD

**Issue by grzegorzCieslik95** [niuware/mui-rte#75]
Hi, i try use this library but i have problem with cursor. I have render method where i render `MUIRichTextEditor`. I have state, which control what i have into textEditor. I try add onChange callback but when i try update my state every time when i write something in textEditor, cursor move to first position.

Do you have any idea how can i fix it? I don't want to use save callBack.

Code here

```
  export default class TextEditor extends React.Component {
     state = {
          editorState: '',
     }

     setEditorState(editorState) {
        this.setState({
             editorState: draftToHtml(convertToRaw(editorState.getCurrentContent())));
        })
      }

      getEditorValue() {
          const contentHTML = convertFromHTML(this.state.editorState);
          const state = ContentState.createFromBlockArray(contentHTML.contentBlocks, contentHTML.entityMap);

           return JSON.stringify(convertToRaw(state))
        }

       render() {
             return (
                  <MUIRichTextEditor 
                      controls={['title', 'bold', 'numberList', 'bulletList', 'undo', 'redo']}
                      label="Test"
                      onChange={::this.setEditorState}
                      value={this.getEditorValue()}
                  />
             )
       }
```

**Comment by niuware** [comment]
Hi @grzegorzCieslik95, thanks for using the package. I have noticed that you are not using the package correctly. You do not require to set another modify the state by yourself as the component does this for you. Also please notice that the `value` property works only as a `defaultValue`. I will change this property name in a next release to be more clear.

Please check out the [examples](https://github.com/niuware/mui-rte/tree/master/examples) directory as well as the [API](https://github.com/niuware/mui-rte/blob/master/README.md) to know how to use the `MUIRichtTextEditor` component.

**Comment by aminkhorrami** [comment]
@niuware hi , i have a case which i want to change the editor value pass to the parent component mean while i'm editing it ! i mean i dont want to use the save button at the end of my work ! is there a way i can do it without losing the currentContent ?
thank you !

` onChange={(value) => {
                    const row = convertToRaw(value.getCurrentContent());
                    props.handleChange(JSON.stringify(convertToRaw(value.getCurrentContent())));
  }}`

and in parent component 

`
 defaultValue={values.content}
 handleChange={(value) => {  setFieldValue('content', value)   }}
`

**Comment by aminkhorrami** [comment]
> @niuware hi , i have a case which i want to change the editor value pass to the parent component mean while i'm editing it ! i mean i dont want to use the save button at the end of my work ! is there a way i can do it without losing the currentContent ?
> thank you !
> 
> ` onChange={(value) => { props.handleChange(JSON.stringify(convertToRaw(value.getCurrentContent()))); }}`
> 
> and in parent component
> 
> ` defaultValue={values.content} handleChange={(value) => { setFieldValue('content', value) }}`


the entire Paretnt component is : 

`
<TextEditor
                                        controllers={[
                                            'bold',
                                            'italic',
                                            'underline',
                                            'strikethrough',
                                            'text-right-align',
                                            'text-center-align',
                                            'text-left-align',
                                            'highlight',
                                            'title',
                                            'numberList',
                                            'bulletList'
                                        ]}
                                        defaultValue={values.content}
                                        handleChange={(value) => {
                                            // setFieldValue('content', JSON.stringify(value));
                                            setFieldValue('content', value);
                                        }}
                                        inlineToolbarAvailable={false}
                                        label={''}
                                    />
`
