### ISSUE TITLE
two instances on one page

### ISSUE THREAD

**Issue by TrejGun** [niuware/mui-rte#81]
Hi guys thanks for this lib. I want to report a bug. Chrome shows these warnings when I have two rtes on page

<img width="1679" alt="Screen Shot 2020-02-26 at 5 49 38 PM" src="https://user-images.githubusercontent.com/185285/75333052-61714600-58c0-11ea-9fdb-8e355eb622a3.png">

**Comment by niuware** [comment]
Thanks, I will check this out.

**Comment by grachet** [comment]
Still appening ^^ It's just because ids are generated the same way so you have many items with the same ID

**Comment by grachet** [comment]
Can you check this, it's annoying and not very hard to solve i think

**Comment by niuware** [comment]
Thank you. From version `1.15.0` you can set an `id` for each editor to avoid this warnings.
