### ISSUE TITLE
How do I focus the editor?

### ISSUE THREAD

**Issue by drxcheng** [niuware/mui-rte#88]
two cases:
1) how do I focus the editor when it is mounted?
2) how do I focus the editor when I click on certain area?

Thanks!

**Comment by thierryMic** [comment]
Hi,

just wondering whether you found the answer to this question?

**Comment by niuware** [comment]
Hi @thierryMic, does [this provided](https://github.com/niuware/mui-rte/blob/master/examples/ref-save/index.tsx) example solves your problem?
