### ISSUE TITLE
bundle size issue

### ISSUE THREAD

**Issue by drxcheng** [niuware/mui-rte#89]
I notice when you import MUI components, you are doing `import { XXX } from '@material-ui/core'`. This will result in the whole MUI package to be built into the bundle.

This should be updated to `import XXX from '@material-ui/core/XXX'`.

**Comment by niuware** [comment]
Thank you for the notes, I will look into this.

**Comment by drxcheng** [comment]
I wish I could fix and send a PR but I'm quite busy right now

**Comment by niuware** [comment]
Updated on version `1.15.1`
