### ISSUE TITLE
Can paste more than max length characters

### ISSUE THREAD

**Issue by drxcheng** [niuware/mui-rte#90]
typing is fine

**Comment by niuware** [comment]
Thank you, this is fixed on version `1.15.0`

**Comment by mooflu** [comment]
There appears to be an off-by-one error in your fix. 
Go to your sandbox https://codesandbox.io/s/mui-rte-basic-ypfdo?fontsize=14
add maxLength={10}
Enter 10 characters, 1234567890, select all, cut, paste -> nothing happens.

**Comment by niuware** [comment]
This is fixed on version `1.15.2`.
