### ISSUE TITLE
"Clear" doesn't clear underline

### ISSUE THREAD

**Issue by drxcheng** [niuware/mui-rte#91]
works for "bold", "italic", "unordered/ordered list"

**Comment by niuware** [comment]
Hi @drxcheng Thanks for your comment. I couldn’t replicate this problem, do you mean when using the "Clear format" control?

**Comment by drxcheng** [comment]
@niuware yes

**Comment by niuware** [comment]
This is working as expected, let me know if you can confirm this.

**Comment by mooflu** [comment]
I can reproduce. Go to your sandbox https://codesandbox.io/s/mui-rte-basic-ypfdo?fontsize=14 
Enter:
"
123
123 [ underlined ]
123
"

Select all, clear selection -> nothing happens

**Comment by niuware** [comment]
This is fixed on version `1.16.2`
