### ISSUE TITLE
How To Create a Menu in a Custom Control?

### ISSUE THREAD

**Issue by jsmwoolf** [niuware/mui-rte#97]
I haven't seen examples of generating a menu from a custom control, so I'm curious to see a code example on to implement a menu.

**Comment by niuware** [comment]
Hi @jsmwoolf What do you mean by menu from a custom control?

**Comment by jsmwoolf** [comment]
Hi @niuware,

What I meant is a popup menu.  You click on a control and it generates a popup menu where you can choose an action to perform.

**Comment by niuware** [comment]
Hi @jsmwoolf this feature is not available at the moment.

**Comment by saintego** [comment]
Any update with this feature?
